graph TD
    subgraph Type Foundries
        TF1(Kontour)
        TF2(Out Of The Dark)
        TF3(Foundry Wilson)
        TF4(WiseType)
        TF5(PatioFoundry)
        TF6(Store Norske Skriftkompani)
        TF7(Matter Of Sorts)
        TF8(The Temporary State)
        TF9(GD Foundry)
        TF10(Source Type)
        TF11(Ultra Kuhl Type Foundry)
        TF12(Positype)
        TF13(FROST)
        TF14(Contemporary Type)
        TF15(Regular Lines Type Foundry)
        TF16(AllCaps)
        TF17(SmussTypeKiosk)
        TF18(SmussStudio)
        TF19(MCKLTypeFoundryAndDesignStudio)
        TF20(SchickToikka)
        TF21(CLT)
        TF22(CalameBureau)
        TF23(OpenFoundry)
        TF24(ProofOfWords)
        TF25(CentralType)
        TF26(FontSpectrum)
        TF27(AlexLescieux)
        TF28(Velvetyne)
    end

    subgraph Persons
        P1(Sibylle Hagmann)
        P2(Philipp Herrmann)
        P3(David Quay)
        P4(Stuart de Rozario)
        P5(Rob Clarke)
        P6(Jacob Wise)
        P7(Vincent Chan)
        P8(Roman Gornitsky)
        P9(Erkin Karamemet)
        P10(Neil Summerour)
        P11(WilliamStormdal)
        P12(JørgenBrynhildsvoll)
        P13(JeremyMickel)
        P14(ClaudeGaramond)
        P15(RobertGranjon)
        P16(JeanJannon)
        P17(FlorianSchick)
        P18(LauriToikka)
        P19(MarkButchko)
        P20(DaniëlMaarleveld)
        P21(EdgarWalthert)
    end

    subgraph Typefaces
        T1(BITRUSH)
        T2(FylRegular)
        T3(Ultimo)
        T4(DepartureMono)
        T5(Edict)
        T6(PoWCovenantMono)
        T7(PowCovenant)
        T8(GTStandard)
        T9(ModernGothic)
    end

    subgraph Locations
        L1(Zurich)
        L2(London)
        L3(Australia)
        L4(Norway)
        L5(Berlin)
        L6(UnitedKingdom)
        L7(Oslo)
        L8(LosAngeles)
        L9(Lausanne)
    end

    subgraph Design Services
        DS1(Retail Typefaces)
        DS2(Custom Fonts)
        DS3(Logo Design)
        DS4(Bespoke Typefaces)
        DS5(Visual Research)
        DS6(Typographic Consultancy)
        DS7(Custom Typeface Development)
        DS8(Custom Typefaces)
        DS9(Logos)
    end

    subgraph Concepts
        C1(Typefaces For Professional Use)
        C2(Graphic Design)
        C3(Contemporary Designs)
        C4(Commoning)
        C5(Design)
        C6(Pedagogy)
        C7(Research Focused)
        C8(Cyrillic Fonts)
        C9(Latin Fonts)
        C10(Typography Built for Branding & Communication)
        C11(Flexible Licenses)
        C12(Custom Tailored Font Design)
        C13(Visual Identities)
        C14(Craft Of Producing Typefaces)
        C15(Uniqueness In Letterforms)
        C16(Warmth In Letterforms)
        C17(Personality In Letterforms)
        C18(Visual Heritage)
        C19(Cultural Nuances)
        C20(Type Designer)
        C21(Lettering Artist)
        C22(Independent Type Foundries)
        C23(Type)
        C24(HistoricalReferences)
        C25(ContemporaryDesign)
        C26(MonospacedPixelFont)
        C27(LoFiTechyVibe)
        C28(CollaborativePlatform)
        C29(Alphabets)
        C30(Letterforms)
        C31(TypographicIdeas)
        C32(RenaissanceFranceType)
        C33(TransitionalType)
        C34(OldStyleType)
        C35(ModernType)
        C36(EdictBold)
        C37(Chiaroscuro)
        C38(SharpSerifs)
        C39(TeardropTerminals)
        C40(ItalicStyle)
        C41(SwashForms)
        C42(DecorativeLigatures)
        C43(Alternates)
        C44(SmallCaps)
        C45(VariableFontFormat)
        C46(WeightAxis)
        C47(OpenSourceFonts)
        C48(NoiseFreeEnvironment)
        C49(FixedWidthFont)
        C50(ScotchRoman)
        C51(Mechanization)
        C52(Standardization)
        C53(LowContrast)
        C54(GraphicDesignStudio)
        C55(DisplayType)
        C56(LibreFonts)
        C57(TypographicStandardization)
        C58(SwissModernistPrinciples)
        C59(Geometry)
        C60(Minimalism)
        C61(DigitalLandscape)
    end

    subgraph Environments
        E1(Print)
        E2(Web)
        E3(Mobile)
    end

    subgraph Years
        Y1(2019)
        Y2(2017)
        Y3(2000)
        Y4(2010)
        Y5(19thCentury)
    end

    TF1 -- offers --> C1
    P1 -- designed_by --> TF1
    TF2 -- based_in --> L1
    TF2 -- run_by --> P2
    TF2 -- offers --> DS1
    DS1 -- for --> E1
    DS1 -- for --> E2
    DS1 -- for --> E3
    TF2 -- specializes_in --> C3
    TF3 -- founded_by --> P3
    TF3 -- founded_by --> P4
    P5 -- is_a --> C20
    P5 -- is_a --> C21
    P5 -- based_in --> L2
    P5 -- offers --> DS3
    P5 -- offers --> DS2
    TF4 -- founded_by --> P6
    TF4 -- established_in --> Y1
    TF4 -- offers --> DS1
    TF4 -- offers --> DS2
    TF5 -- creates --> T1
    TF6 -- based_in --> L4
    TF6 -- focuses_on --> C18
    TF6 -- focuses_on --> C19
    TF7 -- run_by --> P7
    TF7 -- offers --> DS1
    TF7 -- offers --> DS2
    TF7 -- based_in --> L3
    TF7 -- explores --> C4
    TF7 -- explores --> C5
    TF7 -- explores --> C6
    TF7 -- explores --> C23
    TF8 -- creates --> T2
    TF8 -- established_in --> Y2
    TF8 -- founded_by --> P8
    TF8 -- produces --> C8
    TF8 -- produces --> C9
    TF8 -- focuses_on --> C7
    TF9 -- focuses_on --> C10
    TF10 -- offers --> DS1
    TF11 -- based_in --> L5
    TF11 -- offers --> DS1
    TF11 -- offers --> DS2
    TF11 -- offers --> C11
    P9 -- offers --> DS1
    P9 -- offers --> DS4
    P9 -- offers --> DS3
    P9 -- offers --> DS5
    P9 -- offers --> DS6
    P9 -- focuses_on --> C12
    P9 -- creates --> C13
    TF12 -- founded_by --> P10
    TF12 -- established_in --> Y3
    TF12 -- offers --> DS1
    TF12 -- offers --> DS4
    TF12 -- offers --> DS7
    TF12 -- focuses_on --> C14
    TF12 -- values --> C15
    TF12 -- values --> C16
    TF12 -- values --> C17
    TF13 -- based_in --> L6
    TF13 -- offers --> DS1
    TF13 -- offers --> DS8
    TF13 -- combines --> C24
    TF13 -- combines --> C25
    TF16 -- publishes --> C23
    T4 -- is_a_type_of --> C26
    T4 -- has_attribute --> C27
    TF17 -- is_extension_of --> TF18
    TF18 -- based_in --> L7
    TF18 -- run_by --> P11
    TF18 -- run_by --> P12
    TF17 -- explores --> C29
    TF17 -- explores --> C30
    TF17 -- explores --> C31
    TF19 -- based_in --> L8
    TF19 -- run_by --> P13
    TF19 -- publishes --> DS8
    TF19 -- publishes --> DS9
    T5 -- by --> TF20
    T5 -- is_interpretation_of --> C32
    T5 -- influenced_by --> P16
    T5 -- exhibits --> C33
    T5 -- has_style --> C33
    T5 -- has_features --> C38
    T5 -- has_features --> C39
    T5 -- has_features --> C40
    T5 -- has_features --> C41
    T5 -- has_features --> C42
    T5 -- has_features --> C43
    T5 -- has_features --> C44
    T5 -- has_features --> C45
    T5 -- has_features --> C46
    C36 -- is_variation_of --> T5
    C36 -- references --> C37
    TF23 -- provides_platform_for --> C47
    TF24 -- creates --> T6
    T6 -- is_companion_to --> T7
    T6 -- is_a_type_of --> C49
    T7 -- is_interpretation_of --> C50
    T6 -- reflects --> C51
    T6 -- reflects --> C52
    TF20 -- established_in --> Y4
    TF20 -- founded_by --> P17
    TF20 -- founded_by --> P18
    TF20 -- is_a --> C54
    TF25 -- offers --> DS1
    DS1 -- designed_by --> P19
    TF26 -- founded_by --> P20
    TF26 -- founded_by --> P21
    TF26 -- specializes_in --> C55
    TF27 -- based_in --> L9
    TF28 -- offers --> C56
    T8 -- responds_to --> C57
    T8 -- rooted_in --> C58
    C58 -- includes --> C59
    C58 -- includes --> C60
    T8 -- for --> C61
    T5 -- exhibits --> C33
    C50 -- from --> Y5
